<?php
/**
 * GetKillmailsKillmailIdKillmailHashOkVictimItems
 *
 * PHP version 5
 *
 * @category Class
 * @package  ESI
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ESI\Model;

use \ArrayAccess;

/**
 * GetKillmailsKillmailIdKillmailHashOkVictimItems Class Doc Comment
 *
 * @category    Class */
 // @description item object
/** 
 * @package     ESI
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetKillmailsKillmailIdKillmailHashOkVictimItems implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'get_killmails_killmail_id_killmail_hash_ok_victim_items';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'flag' => 'int',
        'itemTypeId' => 'int',
        'quantityDestroyed' => 'int',
        'quantityDropped' => 'int',
        'singleton' => 'int'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'flag' => 'flag',
        'itemTypeId' => 'item_type_id',
        'quantityDestroyed' => 'quantity_destroyed',
        'quantityDropped' => 'quantity_dropped',
        'singleton' => 'singleton'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'flag' => 'setFlag',
        'itemTypeId' => 'setItemTypeId',
        'quantityDestroyed' => 'setQuantityDestroyed',
        'quantityDropped' => 'setQuantityDropped',
        'singleton' => 'setSingleton'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'flag' => 'getFlag',
        'itemTypeId' => 'getItemTypeId',
        'quantityDestroyed' => 'getQuantityDestroyed',
        'quantityDropped' => 'getQuantityDropped',
        'singleton' => 'getSingleton'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['flag'] = isset($data['flag']) ? $data['flag'] : null;
        $this->container['itemTypeId'] = isset($data['itemTypeId']) ? $data['itemTypeId'] : null;
        $this->container['quantityDestroyed'] = isset($data['quantityDestroyed']) ? $data['quantityDestroyed'] : null;
        $this->container['quantityDropped'] = isset($data['quantityDropped']) ? $data['quantityDropped'] : null;
        $this->container['singleton'] = isset($data['singleton']) ? $data['singleton'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if ($this->container['flag'] === null) {
            $invalid_properties[] = "'flag' can't be null";
        }
        if ($this->container['itemTypeId'] === null) {
            $invalid_properties[] = "'itemTypeId' can't be null";
        }
        if ($this->container['singleton'] === null) {
            $invalid_properties[] = "'singleton' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['flag'] === null) {
            return false;
        }
        if ($this->container['itemTypeId'] === null) {
            return false;
        }
        if ($this->container['singleton'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets flag
     * @return int
     */
    public function getFlag()
    {
        return $this->container['flag'];
    }

    /**
     * Sets flag
     * @param int $flag flag integer
     * @return $this
     */
    public function setFlag($flag)
    {
        $this->container['flag'] = $flag;

        return $this;
    }

    /**
     * Gets itemTypeId
     * @return int
     */
    public function getItemTypeId()
    {
        return $this->container['itemTypeId'];
    }

    /**
     * Sets itemTypeId
     * @param int $itemTypeId item_type_id integer
     * @return $this
     */
    public function setItemTypeId($itemTypeId)
    {
        $this->container['itemTypeId'] = $itemTypeId;

        return $this;
    }

    /**
     * Gets quantityDestroyed
     * @return int
     */
    public function getQuantityDestroyed()
    {
        return $this->container['quantityDestroyed'];
    }

    /**
     * Sets quantityDestroyed
     * @param int $quantityDestroyed quantity_destroyed integer
     * @return $this
     */
    public function setQuantityDestroyed($quantityDestroyed)
    {
        $this->container['quantityDestroyed'] = $quantityDestroyed;

        return $this;
    }

    /**
     * Gets quantityDropped
     * @return int
     */
    public function getQuantityDropped()
    {
        return $this->container['quantityDropped'];
    }

    /**
     * Sets quantityDropped
     * @param int $quantityDropped quantity_dropped integer
     * @return $this
     */
    public function setQuantityDropped($quantityDropped)
    {
        $this->container['quantityDropped'] = $quantityDropped;

        return $this;
    }

    /**
     * Gets singleton
     * @return int
     */
    public function getSingleton()
    {
        return $this->container['singleton'];
    }

    /**
     * Sets singleton
     * @param int $singleton singleton integer
     * @return $this
     */
    public function setSingleton($singleton)
    {
        $this->container['singleton'] = $singleton;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\ESI\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\ESI\ObjectSerializer::sanitizeForSerialization($this));
    }
}


